name: Deploy teste nestjs heroku and github actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '14' ]
    steps:
    - uses: actions/checkout@v2

    - name: Test application
      uses: actions/setup-node@v2
      with:
          node-version: ${{ matrix.node }}
    - run: yarn install 
    - run: yarn test
      
    - name: deploy to heroky     
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.API_KEY }}
        heroku_app_name: ${{ secrets.APP_NAME}} 
        heroku_email: ${{ secrets.EMAIL}}
        usedocker: true
    
    
