version: '3'

services:
  bc-database:
    image: mongo:latest
    container_name: mongobc
    ports:
      - "27017:27017"
    volumes:
      - bc-volume:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=bc_user
      - MONGO_INITDB_ROOT_PASSWORD=Toor1234
      - MONGO_INITDB_DATABASE=billing_data

volumes:
  bc-volume: