const languages = new Map([["Fortran", 1957], ["Lisp", 1958], ["COBOL", 1959]]);
const iterator = languages.entries();
console.log(iterator.next());
console.log(iterator.next());
console.log(iterator.next());
console.log(iterator.next());
const values = languages.values();
console.log(values.next());
console.log(values.next());
console.log(values.next());
const keys = languages.keys();
console.log(keys.next());
console.log(keys.next());
console.log(keys.next());
