version: "3"

services:
  app:
    build: .
    command: yarn docker
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    links:
      - mongodb
    depends_on:
      - mongodb
  
  mongodb:
    image: mongo
    container_name: "mongodocker"
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"